
pull_request_rules:
  - name: automatic merge for stable when CI passes and approved + automatic squash-merge
      for master when CI passes and approved
    conditions: []
    actions:
      queue:
queue_rules:
  - name: duplicated default from automatic squash-merge for master when CI passes
      and approved
    queue_conditions:
      - "#approved-reviews-by>=1"
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
      - base=master
    merge_conditions:
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
    update_method: rebase
    merge_method: squash
  - name: duplicated default from automatic merge for stable when CI passes and approved
    queue_conditions:
      - "#approved-reviews-by>=1"
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
      - base=stable
    merge_conditions:
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
    update_method: rebase
    merge_method: rebase
