[package]
name = "av1an-encoders"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
tracing = { workspace = true }

[features]
default = []
